services:
  mongo:
    image: mongo
    volumes:
      - /data/db/mongo
    ports:
      - "27017:27017"
  
  redis:
    image: redis
    volumes:
      - /data/db/redis
    ports:
      - "6379:6379"
  